jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm test
orbs:
  node: circleci/node@1.1.6
version: 2.1
